GET http://localhost:8080/game

###
GET http://localhost:8080/games/22500420

###
GET http://localhost:8080/games/find_player_id?first=lebron&last=james

###
GET http://localhost:8080/games/top?stat=PTS

###
GET http://localhost:8080/games/search?first=lebron&last=james&page=1

###
GET http://localhost:8080/games/averages?first=lebron&last=james

###
GET http://localhost:8080/games/averages/recent?first=lebron&last=james&n=5

###
GET http://localhost:8080/games/trends/range?first=lebron&last=james&from=2024-03-12&to=2025-12-20&stat=REB

###
GET http://localhost:8080/games/trends/recent?first=lebron&last=james&stat=PTS&games=10

###
GET http://localhost:8080/games/heat_check?first=lebron&last=james