spring:
  application:
    name: NBA stats backend

  datasource:
    url: jdbc:postgresql://localhost:5432/heat_check
    username: postgres
    password: 2004
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true